name: Content Integration

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 6 * * 6'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: ubuntu-latest
            nim-flags: '--cc:clang'
          - os: ubuntu-latest
            nim-flags: '--cpu:i386 --passC:-m32 --passL:-m32'
          - os: windows-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Nim
        uses: jiro4989/setup-nim-action@5bbc93d889ba575ed95cde254faa197193690456
      - name: Install cross-compiler
        if: contains(matrix.nim-flags, 'i386')
        run: sudo apt-get update && sudo apt-get -y install gcc-multilib
      - name: Run tests
        run: nim compile ${{matrix.nim-flags}} --run interpreter/tests/test
      - name: Check formatting
        if: runner.os == 'Linux'
        run: |
          find . -name '*.nim' -exec nimpretty --indent:2 {} \;
          git diff --exit-code
